---
- hosts: localhost
  tasks:
#  - name: Build an image and push it to a private repo
#    docker_image:
#      path: ./cabotdocker/
#      name: registry.ansible.com/cabotdocker/appname
#      tag: v1
#      push: yes

#  - name: pull an image
#    docker_image:
#      name: calebmadrigal/nyancat

  - name: Archive image
    docker_image:
      name: calebmadrigal/nyancat
      tag: latest
      archive_path: nyancat.tar
